# Generated by Django 5.2 on 2025-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_image_alter_roomphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
