# Generated by Django 5.2 on 2025-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomtype_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='room_types', to='rooms.equipment'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
