# Generated by Django 5.2 on 2025-05-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtype_equipment_alter_roomtype_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Occupée'), ('CLEANING', 'En nettoyage'), ('MAINTENANCE', 'En maintenance'), ('OUT_OF_ORDER', 'Hors service')], default='AVAILABLE', max_length=20),
        ),
    ]
