# Generated by Django 5.2 on 2025-04-28 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('OCCUPANCY', "Taux d'occupation"), ('REVENUE', 'Revenus'), ('CLIENT_STATS', 'Statistiques clients'), ('SERVICES', 'Services')], default='OCCUPANCY', max_length=20)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.employee')),
            ],
        ),
    ]
